### ISSUE TITLE
Transfer to https://github.com/NullVoxPopuli/coc-ember?

### ISSUE THREAD

**Issue by NullVoxPopuli** [22a/coc-ember#1]
Hello!

I was wondering if you wanted to either collab on this: https://github.com/NullVoxPopuli/coc-ember
and/or transfer the npm package to me?

idk how active you want to be with coc-ember? :)

edit:

just got my version working. yay!

![image](https://user-images.githubusercontent.com/199018/61585814-1675a000-ab33-11e9-8e8f-83b3b86b934e.png)
![image](https://user-images.githubusercontent.com/199018/61585817-3c02a980-ab33-11e9-94be-7facccdfb109.png)

**Comment by 22a** [comment]
> just got my version working. yay!

Can't wait to try it out!
